### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAttribute
  id: EnvironmentPermissionAttribute
  children:
  - System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Security.Permissions.EnvironmentPermissionAttribute.All
  - System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  - System.Security.Permissions.EnvironmentPermissionAttribute.Read
  - System.Security.Permissions.EnvironmentPermissionAttribute.Write
  langs:
  - csharp
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Constructor | System.AttributeTargets.Method, AllowMultiple=true, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public EnvironmentPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  id: All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string All { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Read { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Write { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
