### YamlMime:ManagedReference
items:
- uid: System.Runtime.GCSettings
  id: GCSettings
  children:
  - System.Runtime.GCSettings.IsServerGC
  - System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  - System.Runtime.GCSettings.LatencyMode
  langs:
  - csharp
  name: GCSettings
  nameWithType: GCSettings
  fullName: System.Runtime.GCSettings
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static class GCSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.GCSettings.IsServerGC
  id: IsServerGC
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  name: IsServerGC
  nameWithType: GCSettings.IsServerGC
  fullName: System.Runtime.GCSettings.IsServerGC
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static bool IsServerGC { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  id: LargeObjectHeapCompactionMode
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  name: LargeObjectHeapCompactionMode
  nameWithType: GCSettings.LargeObjectHeapCompactionMode
  fullName: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.Runtime.GCLargeObjectHeapCompactionMode LargeObjectHeapCompactionMode { get; set; }
    return:
      type: System.Runtime.GCLargeObjectHeapCompactionMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.GCSettings.LatencyMode
  id: LatencyMode
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  name: LatencyMode
  nameWithType: GCSettings.LatencyMode
  fullName: System.Runtime.GCSettings.LatencyMode
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.Runtime.GCLatencyMode LatencyMode { get; set; }
    return:
      type: System.Runtime.GCLatencyMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Runtime.GCSettings.IsServerGC
  parent: System.Runtime.GCSettings
  isExternal: false
  name: IsServerGC
  nameWithType: GCSettings.IsServerGC
  fullName: System.Runtime.GCSettings.IsServerGC
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  parent: System.Runtime.GCSettings
  isExternal: false
  name: LargeObjectHeapCompactionMode
  nameWithType: GCSettings.LargeObjectHeapCompactionMode
  fullName: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
- uid: System.Runtime.GCLargeObjectHeapCompactionMode
  parent: System.Runtime
  isExternal: false
  name: GCLargeObjectHeapCompactionMode
  nameWithType: GCLargeObjectHeapCompactionMode
  fullName: System.Runtime.GCLargeObjectHeapCompactionMode
- uid: System.Runtime.GCSettings.LatencyMode
  parent: System.Runtime.GCSettings
  isExternal: false
  name: LatencyMode
  nameWithType: GCSettings.LatencyMode
  fullName: System.Runtime.GCSettings.LatencyMode
- uid: System.Runtime.GCLatencyMode
  parent: System.Runtime
  isExternal: false
  name: GCLatencyMode
  nameWithType: GCLatencyMode
  fullName: System.Runtime.GCLatencyMode
